Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 151, in detect_game_window
    self.log_message("--- 开始检测游戏窗口 ---", clear=True)
TypeError: log_message() got an unexpected keyword argument 'clear'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\SGJQ_Gemini\dashboard_main.py", line 151, in detect_game_window
    self.log_message("--- 开始检测游戏窗口 ---", clear=True)
TypeError: log_message() got an unexpected keyword argument 'clear'